# Generated by Django 3.2.6 on 2021-08-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoriosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('lab_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('estado', models.CharField(choices=[('M', 'En Mantenimiento'), ('D', 'Disponible')], max_length=100, verbose_name='Estado')),
                ('aforo', models.IntegerField(verbose_name='Aforo')),
            ],
        ),
    ]
